### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR when replacing "4chan" with "4webm" in a thread url

### ISSUE THREAD

**Issue by leewdch** [ScottyFillups/4webm#1]
Using latest version of Chrome x64. Manually visiting [the website](http://www.4webm.org/) and entering the 4chan url works fine.  I mean, it's still flagged as not secure because it doesn't use https but at least it let me in this way.

**Comment by ScottyFillups** [comment]
Hey, thanks for bringing that up :smile: 

I'll look into setting up SSL for 4webm.org

**Comment by ScottyFillups** [comment]
Yay! :sparkles: https://www.4webm.org/ :sparkles: works now!

@leewdch SSL has been set up. Thanks for submitting your issue :smile:

Note to self for setting up SSL with Heroku in the future:

* https://medium.com/@franxyzxyz/setting-up-free-https-with-heroku-ssl-and-lets-encrypt-80cf6eac108e
* https://devcenter.heroku.com/articles/ssl#manually-uploading-certificates-and-intermediaries

**Comment by ScottyFillups** [comment]
Eh, actually turns out I need to set up certs for each subdomain; I'll do https://boards.4webm.org/ some time soon :wink:

**Comment by ScottyFillups** [comment]
Done! :smile:
